#include "i1.h"
#include "i2.h"
#include "i3.h"
#include "i4.h"
#include "i5.h"
#include "i6.h"
#include "i7.h"
#include "i8.h"
#include "i9.h"
#include "i10.h"
#include "i11.h"
#include "i12.h"
#include "i13.h"
#include "i14.h"
#include "i15.h"
void imageSelector(ILI9341_Handler_t *ili9341_handler,uint16_t num);
